### ISSUE TITLE
testsuite error with test-unit 3.6.4

### ISSUE THREAD

**Issue by mtasaka** [ruby-gettext/gettext#109]
gettext 3.4.9 testsuite causes error with test-unit 3.6.4

```
+ ruby -Ilib:test test/run-test.rb
Loaded suite test/run-test

269 tests, 627 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------
63.85 tests/s, 148.83 assertions/s/usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/testcase.rb:580:in 'run': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /builddir/build/BUILD/rubygem-gettext-3.4.9-build/gettext-3.4.9/usr/share/gems/gems/gettext-3.4.9/test/tools/test_msginit.rb:40:in 'block (2 levels) in TestToolsMsgInit#run'
	from /builddir/build/BUILD/rubygem-gettext-3.4.9-build/gettext-3.4.9/usr/share/gems/gems/gettext-3.4.9/test/tools/test_msginit.rb:39:in 'Dir.chdir'
	from /builddir/build/BUILD/rubygem-gettext-3.4.9-build/gettext-3.4.9/usr/share/gems/gems/gettext-3.4.9/test/tools/test_msginit.rb:39:in 'block in TestToolsMsgInit#run'
	from /usr/share/ruby/tmpdir.rb:109:in 'Dir.mktmpdir'
	from /builddir/build/BUILD/rubygem-gettext-3.4.9-build/gettext-3.4.9/usr/share/gems/gems/gettext-3.4.9/test/tools/test_msginit.rb:38:in 'TestToolsMsgInit#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:68:in 'Test::Unit::TestSuiteRunner#run_test'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:60:in 'block in Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:59:in 'Array#each'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:59:in 'Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:37:in 'Test::Unit::TestSuiteRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/testsuite.rb:52:in 'Test::Unit::TestSuite#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:68:in 'Test::Unit::TestSuiteRunner#run_test'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:60:in 'block in Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:59:in 'Array#each'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:59:in 'Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:37:in 'Test::Unit::TestSuiteRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/testsuite.rb:52:in 'Test::Unit::TestSuite#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:68:in 'Test::Unit::TestSuiteRunner#run_test'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:60:in 'block in Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:59:in 'Array#each'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:59:in 'Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:37:in 'Test::Unit::TestSuiteRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/testsuite.rb:52:in 'Test::Unit::TestSuite#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnermediator.rb:72:in 'Test::Unit::UI::TestRunnerMediator#run_suite'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnermediator.rb:49:in 'block (3 levels) in Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnermediator.rb:44:in 'Kernel#catch'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnermediator.rb:44:in 'block (2 levels) in Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/test-suite-runner.rb:17:in 'Test::Unit::TestSuiteRunner.run_all_tests'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnermediator.rb:43:in 'block in Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnermediator.rb:107:in 'Test::Unit::UI::TestRunnerMediator#with_listener'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnermediator.rb:42:in 'Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunner.rb:40:in 'Test::Unit::UI::TestRunner#start_mediator'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunner.rb:25:in 'Test::Unit::UI::TestRunner#start'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/ui/testrunnerutilities.rb:24:in 'Test::Unit::UI::TestRunnerUtilities#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/autorunner.rb:492:in 'block in Test::Unit::AutoRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/autorunner.rb:548:in 'Test::Unit::AutoRunner#change_work_directory'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/autorunner.rb:491:in 'Test::Unit::AutoRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.4/lib/test/unit/autorunner.rb:67:in 'Test::Unit::AutoRunner.run'
	from test/run-test.rb:40:in 'block in <main>'
	from test/run-test.rb:36:in 'Dir.chdir'
	from test/run-test.rb:36:in '<main>'
```

Perhaps due to https://github.com/test-unit/test-unit/pull/263

**Comment by kou** [comment]
Could you try 3.5.0?

**Comment by mtasaka** [comment]
Okay, working as well as #110 . Thank you.
