### ISSUE TITLE
gettext 3.1.5 seems to require >=text 1.3.0

### ISSUE THREAD

**Issue by graaff** [ruby-gettext/gettext#37]
With text 1.2.3 installed I am seeing test failures similar to 

```
Error: test_obsolete_entry(TestToolsMsgMerge::TestMerger)
  ArgumentError: wrong number of arguments (3 for 2)
/usr/lib64/ruby/gems/1.9.1/gems/text-1.2.3/lib/text/levenshtein.rb:32:in `distance'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/tools/msgmerge.rb:254:in `compute_distance'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/tools/msgmerge.rb:227:in `block in find'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/tools/msgmerge.rb:226:in `each'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/tools/msgmerge.rb:226:in `find'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/tools/msgmerge.rb:124:in `merge_definition'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/tools/msgmerge.rb:98:in `block in merge'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/po.rb:174:in `each_value'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/po.rb:174:in `each'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/lib/gettext/tools/msgmerge.rb:96:in `merge'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/test/tools/test_msgmerge.rb:39:in `merge'
/var/tmp/portage/dev-ruby/ruby-gettext-3.1.5/work/ruby19/ruby-gettext-3.1.5/test/tools/test_msgmerge.rb:305:in `test_obsolete_entry'
     302:     def test_obsolete_entry
     303:       @po["hello"] = "bonjour"
     304:       @pot["hi"] = "salut"
  => 305:       merged_po = merge
     306: 
     307:       assert_equal("salut", merged_po["hi"].msgstr)
     308:       assert_false(merged_po.has_key?("hello"))
```

Upgrading to text 1.3.0 causes all tests to pass.

**Comment by kou** [comment]
Good catch!
I've fixed it and released a new version.
