### ISSUE TITLE
LoadError with ruby 3.1.0

### ISSUE THREAD

**Issue by Na0ki** [ruby-gettext/gettext#92]
`mathn` LoadError occures when calling `GetText::Tools::MsgFmt.run` with ruby 3.1.0.

```
/home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/mo.rb:178:in `require': cannot load such file -- mathn (LoadError)
        from /home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/mo.rb:178:in `next_prime'
        from /home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/mo.rb:217:in `save_to_stream'
        from /home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/mo.rb:292:in `block in save_to_file'
        from /home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/mo.rb:292:in `open'
        from /home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/mo.rb:292:in `save_to_file'
        from /home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/tools/msgfmt.rb:58:in `run'
        from /home/ahiru/work/ruby/gettext-ruby3.1.0/vendor/bundle/ruby/3.1.0/gems/gettext-3.4.1/lib/gettext/tools/msgfmt.rb:38:in `run'
        from app.rb:3:in `<main>'
```

It looks like because [ruby 3.1.0 extracted `prime` from default gem to bundled gem](https://stdgems.org/#bundled-gems-in-ruby-310). that causes LoadError when requiring prime gem, then fallback to rescue block and causing mathn LoadError.

Tested gettext 3.4.1 with ruby 3.1.0, 3.0.3. 3.0.3 works fine without LoadError.

**Comment by kou** [comment]
Good catch!

**Comment by Na0ki** [comment]
Tried 3.4.2 and confirmed that it works fine.
Thank you very much for your quick action!
